name: RTL CI

on:
  push:
    paths:
      - "rtl/**"
      - "sim/**"

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Install Verilator
        run: sudo apt-get update && sudo apt-get install -y verilator

      - name: Build & Run
        run: |
          cd sim
          make